# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Preview
permissions:
  contents: read
  id-token: write
  deployments: write
  pages: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18

      - name: Install deps
        run: |
          GOPATH=$(pwd)/.go go mod download
          npm ci

      - name: Test
        run: GOPATH=$(pwd)/.go go test ./analyze

      - name: Build
        run: |
          npm run prepare:go-wasm-runtime
          GOPATH=$(pwd)/.go npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.2
